---
author: Inês Grazieli Kirchner
title: Direito Constitucional - Dos princípios fundamentais à Constituição Econômica
local: São José - SC
instituicao: FACULDADE DE SANTA CATARINA - FASC
date: '2018'
titulacao: Bacharel em Direito
curso: Direito
programa: Programa de Pós-Graduação em XXX
area_de_concentracao: Direito
linha_de_pesquisa: ''
coorientador: ''
orientador: Prof. Ricardo Espíndola
referencias_caminho: referencias.bib
proposito: ''
resumo: O objetivo deste trabalho é suscitar uma discussão sobre as obrigações legais
  das principais instituições brasileiras responsáveis pela política monetária, a
  luz dos princípios fundamentais da Constituição Federal de 1988 e da Declaração Universal
  de Direitos Humanos. Para isto, foi estudada a estrutura legal que compete ao Sistema
  Financeiro Nacional, em comparação ao existente em outras partes do mundo, em especial
  aos EUA; foram analisados dados econômicos do país desde a implantação do Plano
  Real, com maior foco sobre o período que compreende à vigência do regime de metas
  de inflação; e por fim foram analisados estudos e debates teóricos sobre política
  monetária no Brasil e no mundo. Após uma análise final, considerando-se os princípios
  fundamentais e os direitos sociais da Constituição Federal de 1988 e, em comparação
  com o estabelecido como função de outros Bancos Centrais ao redor do mundo, propõem-se
  a reformulação das atribuições legais do Banco Central do Brasil, qual órgão executivo
  central do sistema financeiro, com vistas a exigir que se cumpra o princípio fundamental  dos
  "valores sociais do trabalho e da livre iniciativa" (inciso IV do artigo 1º),  direito
  social ao trabalho (artigo 6º da CF) e, porque não, o direito universal "ao trabalho,
  à livre escolha de emprego, a condições justas e favoráveis de trabalho e à proteção
  contra o desemprego" (artigo 23 da DUDH).
palavras_chave: 'Direito Constitucional. Princípios Fundamentais. Autoridades Monetárias.'
keywords: ''
abstract_texto: ''
resumen: ''
palabras_clave: ''
resume: ''
mots_cles: ''
siglas:
- s: ABNT
  d: Associação Brasileira de Normas Técnicas
simbolos: 
dedicatoria: ''
agradecimentos: ''
epigrafe: ''
avaliador2: Nome-do-Prof-Convidado2
aprovacao_dia: '1'
avaliador1: Nome-do-Prof-Convidado1
avaliador3: ''
graduacao: true
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: Monografia
incluir_ficha_catalografica: false
folha_de_aprovacao: true
projeto: false
apendices: false
anexos: false
errata: false
referencias_sistema: alf, versalete, abnt-emphasize = bf, abnt-full-initials = yes, abnt-repeated-author-omit = yes
lista_ilustracoes: false
lista_tabelas: false

---
